name: Deploy Docs

on:
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  build_deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"

      - name: Install MkDocs and Material for MkDocs
        run: |
          pip install mkdocs
          pip install mkdocs-material

      - name: Build the documentation
        run: mkdocs build --clean --config-file docs/mkdocs.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          force_orphan: true
