name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-root

      - name: Run tests with coverage
        run: poetry run pytest --cov=src --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests,integration
          name: codecov-sharetracker
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
